<?php

namespace miniShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedProductsRepository extends EntityRepository
{
    public function findOrderedProductsByOrder($orderId)
    {
        $em=$this->getEntityManager();
        $query = $em->createQuery('SELECT b.number, u.name, u.size, u.price FROM miniShopBundle:OrderedProducts AS b
                JOIN b.products AS u
                WHERE b.orders = :id')
            ->setParameter('id', $orderId)
            ->getResult();

        return $query;
    }
}
