<?php

namespace miniShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function findFilteredProductsBySize($size)
    {
        $em=$this->getEntityManager();
        $query = $em->createQuery('SELECT b FROM miniShopBundle:Products AS b
                WHERE b.size = :productSize')
            ->setParameter('productSize', $size)
            ->getResult();

        return $query;
    }
}
